name: hello world
'on':
  push:
  pull_request:
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: install_libgbm
        run: |
          sudo apt-get install libgbm1 -y
      - name: install_libxkbcommon
        run: |
          sudo apt-get install libxkbcommon-x11-0 -y
      - name: Set up Chrome
        uses: browser-actions/setup-chrome@latest
        with:
            chrome-version: stable

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.4
        with:
            maven-version: 3.8.2

      - name: Build and Test with Maven
        run: mvn clean install
        continue-on-error: false

      - name: Run Automation Test suite
        run: mvn clean test
        continue-on-error: true

      - run: echo hi > world.txt
      - uses: actions/upload-artifact@v3
        with:
          path: world.txt
