name: hello world
'on':
  push:
  pull_request:
jobs:
  hello:
    runs-on: [self-hosted, linux, ARM64]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up JDK 17
          uses: actions/setup-java@v1
          with:
            java-version: 17
      - name: Build and Test with Maven
          env:
            GITHUB_USERNAME: Abhinay6709
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: mvn test
          continue-on-error: false

